# Generated by Django 5.2 on 2025-04-17 21:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Deployed', 'Deployed'), ('Destroyed', 'Destroyed'), ('Decommissioned', 'Decommissioned')], default='Available', max_length=20)),
                ('decommissioned_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
