services:
  - type: web
    name: imf-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: |
      gunicorn imf_api.wsgi:application --chdir imf_api
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: imf_api.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - fromGroup: imf-api-env