services:
  - type: web
    name: imf-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn imf_api.wsgi:application --chdir imf_api
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - fromGroup: imf-api-env
